### ISSUE TITLE
does it need mysql-connector files still？

### ISSUE THREAD

**Issue by liufeijin** [Roslaniec/MariaCpp#3]
i saw the file time.hpp includes mysql.h.
So we must be download something from mysql website?
best regards,
jeff

**Comment by Roslaniec** [comment]
Hi,

Sure you need MySQL (or MariaDB) client development files (headers).
Install appropriate package, eg. libmariadb-dev or mariadb-devel.

Best Regards,
Karol Roslaniec

**Comment by liufeijin** [comment]
Hi Many thanks!
Do you mean only the .h files in  mysql-dev pack?
If only need the .h file, what is the requirement for the /mysql/include folder place?

**Comment by Roslaniec** [comment]
Hi,

You simply need MySQL Connector/C (https://dev.mysql.com/downloads/connector/c/) or equivalent MariaDB library.

Best Regards,
Karol Roslaniec

**Comment by liufeijin** [comment]
Hi Roslaniec
I include mysql connector after build get below error
![11](https://user-images.githubusercontent.com/19425403/52562608-fb8f5900-2e39-11e9-92d9-92bb46cd9551.png)

**Comment by Roslaniec** [comment]
Hi,

Please check the newest version. I've just committed the change that should solve it.

Best Regards,
Karol Roslaniec

**Comment by liufeijin** [comment]
Hi Karol Roslaniec
Many thanks for your help!
There are 3 problem still.  
1: __null to be change to nullprt  ( i use qt5.12) 
2: add a hpp file to tie.hpp  #include <string>
3: MAX_NO_FIELD_TYPES  is not identifier    I  added // to avoid the error.

After changing above , when build it , i got error as below
![4](https://user-images.githubusercontent.com/19425403/52611728-d6dec400-2ec1-11e9-86ed-611e50163d96.png)

i used QT5.12 WINDOWS10 

[MariaCpp.ZIP](https://github.com/Roslaniec/MariaCpp/files/2854132/MariaCpp.ZIP)  your code after modified 3 items above .
[untitled7.ZIP](https://github.com/Roslaniec/MariaCpp/files/2854134/untitled7.ZIP)  my test project file

Could you have a look where is the problem?

**Comment by Roslaniec** [comment]
Hi,

You need to link you project with libmysql client library (did you build/install Connector/C library?)

BTW, why don't you use MySQL Connector/C++ library (https://dev.mysql.com/downloads/connector/cpp/)?
It has the same functionality, but better documentation.

Best Regards,
Karol Roslaniec

**Comment by liufeijin** [comment]
Hi 
I have include MySql connector  head file.
I don't want to use MySql connector lib as my app is on android .
If use MySql connector lib shall be build the special lib for android platform ,i tried and search many times how to build MySql connector lib for android platform,failed.
So i want to find third party source code include into my project and use QT for android to build the apk.
Best regards,
jeff

**Comment by Roslaniec** [comment]
Hi,

But MariaCpp depends on Connector/C library (compiled+installed).

For Android, you should rather try JDBC Connector/J driver.
There are some hints on the web, how to do this:
https://parallelcodes.com/android-connect-mysql-database/

Some people suggest to create HTTP server between your app and MySQL server:
http://www.helloandroid.com/tutorials/connecting-mysql-database
https://stackoverflow.com/questions/12233145/connecting-to-mysql-from-android-with-jdbc

Best Regards,
Karol
